### PR TITLE
Update to use Spatie Permission 3.0.0 which uses L6

### PR DESCRIPTION
**Pull request by eldor**
Update composer to use spatie/laravel-permission 3.0.0 with Laravel 6 upgrade

### CODE REVIEW

**Comment by eldor** [comment]
@paras-malhotra any change this can be merged in, so the package can continued to be used in Laravel? Thx

**Comment by simpel** [comment]
This would be awesome!

**Comment by tumainimosha** [comment]
Looking forward to this.

this addresses issue #21

**Comment by tumainimosha** [comment]
@paras-malhotra 

Please assist to merge this issue.

**Comment by shirshak55** [comment]
its dead i guess.

**Comment by paras-malhotra** [comment]
Merged https://github.com/insenseanalytics/laravel-nova-permission/pull/25

**Pull request closed without merging**
